spring:
  data:
    neo4j:
      username: neo4j
      password: admin
      uri: bolt://localhost:7687
      #uri: bolt://10.176.34.86:9687
      #uri: bolt://10.176.34.83:7687

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
server:
  port: 8080

config:
  starter:
    cochange: true
    depends_on: true
    clone_group: true
    module_clone: true
    aggregation_clone: true
    smell: true
    modularity: false
    export_cyclic_dependency : false

data:
  project_analyse_threads_count: -1
  project_config: src/main/resources/project/source-test.json
  dynamic_analyse: false
  git_analyse: true
  lib_analyse: false
  clone_analyse: true

  neo4j:
    delete: true
    data_path: C:\\LocalProgram\\neo4j\\neo4j-community-4.2.3\\data
    database_name: multi.dependency.db

  serialize_path: D:\\workspace\\multiple-dependency-project\\RepositoryService-source.txt

  test: this property is for YamlUtilsTest
